spring:
  data:
    mongodb:
      host: ${host}
      port: ${port}
      database: ${database}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG