DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME  VARCHAR(255) NOT NULL,
    SECOND_NAME VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX AUTHORS_FULLNAME_IDX ON AUTHORS (FIRST_NAME, SECOND_NAME);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    TITLE       VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(512),
    AUTHOR_ID   INT          NOT NULL,
    GENRE_ID    INT          NOT NULL,
    foreign key (AUTHOR_ID) references AUTHORS,
    foreign key (GENRE_ID) references GENRES
);